version: "3"

services:
    app:
        build: .
        command: npm start
        image: egm21
        ports:
            - "30100:3010"
        depends_on:
            - mongo
        links:
            - mongo
        tty: true
        restart: always
    mongo:
        image: mongo
        volumes:
            - ./data/db:/data/db
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_MONGODB_PORT=27017
        depends_on:
            - mongo
        ports:
          - "30200:8081"
        restart: always