version: "3"

services:
    app:
        build: .
        command: npm start
        image: egm21
        ports:
            - "30100:3010"
        volumes:
            - .:/usr/app
        tty: true
